modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/PieKing1215/SneakAnimation/issues"
[[mods]]
modId="sneakanimation"
version="0.1.1"
displayName="SneakAnimation"
displayURL="https://github.com/PieKing1215/SneakAnimation"
logoFile="logo.png"
#credits=""
authors="PieKing1215"
description='''
Lets you tweak the sneak animation.'''

[[dependencies.sneakanimation]]
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.sneakanimation]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"
[[dependencies.sneakanimation]]
    modId="cloth-config2"
    mandatory=true
    versionRange="[1.4,)"
    ordering="NONE"
    side="CLIENT"