modLoader="javafml"
loaderVersion="[33,)"
license="GPL v3.0"
issueTrackerURL="https://github.com/PieKing1215/SneakAnimation/issues"
[[mods]]
modId="sneakanimation"
version="0.1.1"
displayName="SneakAnimation"
displayURL="https://github.com/PieKing1215/SneakAnimation"
logoFile="logo.png"
#credits=""
authors="PieKing1215"
description='''
Lets you tweak the sneak animation.'''

[[dependencies.sneakanimation]]
    modId="forge"
    mandatory=true
    versionRange="[33,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.sneakanimation]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.2]"
    ordering="NONE"
    side="BOTH"
[[dependencies.sneakanimation]]
    modId="cloth-config"
    mandatory=true
    versionRange="[4.0,)"
    ordering="NONE"
    side="CLIENT"